usr/share/unfold/static
usr/share/unfold/templates
usr/share/unfold/apache
usr/share/unfold/auth
usr/share/unfold/insert_above
usr/share/unfold/manifold
usr/share/unfold/plugins
usr/share/unfold/unfold
usr/share/unfold/views
usr/share/unfold/myslice
usr/share/unfold/sample
usr/share/unfold/trash
usr/share/unfold/debug_platform
manage.py usr/share/unfold/manage.py
/etc/apache2/sites-available/myslice.conf
