# we need 3 pieces
# spin.min.js - core - see URL
# jquery.min.js - the jqeury plugin - see URL
# spin.presets.js - our own settings defined as spin_presets
all:
	cat spin.min.js jquery.spin.js spin.presets.js > spin.all.js
